insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("수박", "fruit", 15000 , "희원농가", 10, "달달하고 꽉 찬 꿀수박")
insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("전복", "seafood", 20000 , "은빈수산", 30, "국내산 전복 300g")
insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("초콜렛", "chocolate", 1200 , "지원상점", 100, "쌉싸름한 다크 초콜렛")
insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("등심", "beef", 38000 , "현조정육", 4, "스테이크용 등심 소고기")
insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("체리", "fruit", 8000 , "윤지과수원", 80, "직접 키운 체리 한 박스")
insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("식빵", "bread", 5000 , "효진빵집", 15, "매일 아침 7시 구워지는 식빵")
insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("립스틱", "cosmetics", 12000 , "민지뷰티", 300, "쿨톤을 위한 립스틱")
insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("노트북", "electronic", 1300000 , "지원전자", 45, "지원전자 최신형 노트북")
insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("귤", "fruit", 10000 , "윤하농장", 90, "하우스 귤 한 박스")
insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("커피", "coffee", 6000 , "재경커피", 250, "에티오피아산 원두로 로스팅")
